/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LecturerDashboardUI extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboardUI
     */
    public LecturerDashboardUI() {
        initComponents();
    }

    LecturerDashboardUI(String username) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_label = new javax.swing.JLabel();
        Combo_button = new javax.swing.JComboBox<>();
        Logout_button = new javax.swing.JButton();
        Confirm_button = new javax.swing.JButton();
        text2_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        text_label.setText("Lecturer Dashboard");

        Combo_button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Consultation Slots", "Appointments Dashboard", "Provide Feedback", "View Feedback" }));

        Logout_button.setText("Log Out");
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        Confirm_button.setText("Confirm");
        Confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_buttonActionPerformed(evt);
            }
        });

        text2_label.setText("Welcome Back !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Logout_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirm_button)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(text2_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Combo_button, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2_label)
                .addGap(24, 24, 24)
                .addComponent(Combo_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout_button)
                    .addComponent(Confirm_button))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_buttonActionPerformed
        String selectedValue = Combo_button.getSelectedItem().toString();
        
        switch (selectedValue) {
        case "Add Consultation Slots":
            SetSlot SetSlotScreen = new SetSlot();
            SetSlotScreen.setVisible(true);
            this.dispose();
            break;
            

        case "Appointments Dashboard":
            AppointmentsDashboard AppointmentDashboardScreen = new AppointmentsDashboard();
            AppointmentDashboardScreen.setVisible(true);
            this.dispose();
            break;
            

        case "Provide Feedback":
            LecturerFeedback LecturerFeedbackScreen = new LecturerFeedback();
            LecturerFeedbackScreen.setVisible(true);
            this.dispose();
            break;
            
            
        case "View Feedback":
            ViewFeedbackUI ViewFeedbackUIScreen = new ViewFeedbackUI();
            ViewFeedbackUIScreen.setVisible(true);
            this.dispose();
            break;
            
            
        

        default:
            // Handle invalid or unrecognized values
            JOptionPane.showMessageDialog(this, "Please select a valid option.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_Confirm_buttonActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        LoginUI LoginUIScreen = new LoginUI();
        LoginUIScreen.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Logout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerDashboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_button;
    private javax.swing.JButton Confirm_button;
    private javax.swing.JButton Logout_button;
    private javax.swing.JLabel text2_label;
    private javax.swing.JLabel text_label;
    // End of variables declaration//GEN-END:variables
}
