/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        LogIn_button = new javax.swing.JButton();
        Register_button = new javax.swing.JButton();
        Username_field = new javax.swing.JTextField();
        Password_field = new javax.swing.JPasswordField();
        Exit_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Username_label.setText("Username");

        Password_label.setText("Password");

        LogIn_button.setText("Log In");
        LogIn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_buttonActionPerformed(evt);
            }
        });

        Register_button.setText("Register");
        Register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_buttonActionPerformed(evt);
            }
        });

        Username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_fieldActionPerformed(evt);
            }
        });

        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });

        Exit_button.setText("Exit");
        Exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOG IN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Password_label)
                        .addComponent(Username_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Exit_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Password_field)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Register_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(LogIn_button))
                    .addComponent(Username_field))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_label)
                    .addComponent(Username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_label)
                    .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogIn_button)
                    .addComponent(Register_button)
                    .addComponent(Exit_button))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_buttonActionPerformed

    private void Register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_buttonActionPerformed
        RegisterUI registerScreen = new RegisterUI();
    
    // Set the current JFrame (this) to invisible or dispose if you want to close it
    this.setVisible(false); // Optionally, you can use this.dispose();
    
    // Show the RegisterUI JFrame
    registerScreen.setVisible(true);
    }//GEN-LAST:event_Register_buttonActionPerformed

    private void LogIn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_buttonActionPerformed
            // Get values from the fields
    String username = Username_field.getText();
    String password = Password_field.getText();

    // Validate fields
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and Password are required.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Read the user_data.txt to validate login
    try (BufferedReader reader = new BufferedReader(new FileReader("user_data.txt"))) {
        String line;
        boolean isAuthenticated = false;
        String role = "";

        while ((line = reader.readLine()) != null) {
            if (line.startsWith("Username: ")) {
                String storedUsername = line.substring(10).trim();

                // Check if the username matches
                if (storedUsername.equals(username)) {
                    // Read the next line for the password
                    String passwordLine = reader.readLine();
                    String storedPassword = passwordLine.substring(10).trim();

                    // Validate the password
                    if (storedPassword.equals(password)) {
                        isAuthenticated = true;

                        // Read the role from the file
                        String roleLine = reader.readLine();
                        role = roleLine.substring(6).trim(); // Extract "Role: " value
                        break;
                    }
                }
            }
        }

        if (isAuthenticated) {
            // Redirect based on the role
            if (role.equalsIgnoreCase("Lecturer")) {
                JOptionPane.showMessageDialog(this, "Login successful! Redirecting to Instructor Dashboard.", "Success", JOptionPane.INFORMATION_MESSAGE);
                LecturerDashboardUI instructorDashboard = new LecturerDashboardUI();
                instructorDashboard.setVisible(true);
            } else if (role.equalsIgnoreCase("Student")) {
                JOptionPane.showMessageDialog(this, "Login successful! Redirecting to Student Dashboard.", "Success", JOptionPane.INFORMATION_MESSAGE);
                Dashboard studentDashboard = new Dashboard();
                studentDashboard.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Unknown role. Unable to redirect.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose(); // Close the current LoginUI window
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading user data file.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_LogIn_buttonActionPerformed

    private void Username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_fieldActionPerformed

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_button;
    private javax.swing.JButton LogIn_button;
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel Password_label;
    private javax.swing.JButton Register_button;
    private javax.swing.JTextField Username_field;
    private javax.swing.JLabel Username_label;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
